### PR TITLE
[MM-52924] Update mattermost server dependency

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

Just updating the server dependency so that we can build the plugin side.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-52924

### CODE REVIEW

**Review by cpoile — APPROVED** [review]
Should we also make the change:
`github.com/mattermost/mattermost-server/server/public` -> `github.com/mattermost/mattermost/server/public` ?

**Comment by streamer45** [comment]
> Should we also make the change: `github.com/mattermost/mattermost-server/server/public` -> `github.com/mattermost/mattermost/server/public` ?

Yeah, I'll look into this. Unfortunately I worked on these changes like an hour before we renamed :/

**Comment by streamer45** [comment]
Will have to wait for https://mattermost.atlassian.net/browse/MM-53032 to do the above.

**Review by cpoile — APPROVED** [review]
👍

**Pull request merged**
