### PR TITLE
Support client self registration

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR adds a new config setting to allow clients to self-register to the service.
I had to make a few seemingly unrelated changes to the store to make the registration operation safe for concurrent use. 

Companion PR is https://github.com/mattermost/mattermost-plugin-calls/pull/43

### CODE REVIEW

**Review by cpoile — DISMISSED** [review]
👍

**Comment by streamer45** [comment]
@spirosoik Could you give this a quick approval to unblock the merge? I've raised this in https://community-daily.mattermost.com/core/pl/68yxqyjn6j8euyhmoppfb5rzww

**Comment by streamer45** [comment]
@cpoile Have to re-request approval on this as repository related policies have changed (had to sign the commits).

**Review by cpoile — APPROVED** [review]
😄

**Pull request merged**
