### PR TITLE
Init

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

Literally just preparing the ground. No implementation yet. Salient points of the PR:

- Skeleton for the `rtcd` command.
- Config uses [TOML](https://toml.io/). This is totally opinionated. I wanted to part ways with JSON which I always felt as a rather poor choice for the purpose. 
- Logger. We still use `mlog` but set it up ourselves so we can avoid some unnecessary dependencies.
- Makefile with basic actions (lint, test, build).
- Several tests. Trying to get off on the right foot on this front.

### CODE REVIEW

**Review by cpoile — APPROVED** [review]
👍

**Comment by cpoile** [comment]
Hope you don't mind if I merge? (We didn't discuss merge-etiquette... :)

**Comment by streamer45** [comment]
> Hope you don't mind if I merge? (We didn't discuss merge-etiquette... :)

Don't mind only thing I see these didn't get squashed somehow. It's okay for now but in the future we may consider squashing to avoid spurious commits.

**Comment by cpoile** [comment]
@streamer45 Hm, strange -- I bet there's a setting on the repo to force squash-and-merge?

**Comment by streamer45** [comment]
> @streamer45 Hm, strange -- I bet there's a setting on the repo to force squash-and-merge?

Possibly although I am not admin as it's all automated through Gitlab. I think the option is there and once used it gets automatically saved as default option. We can have a look in the next PR I guess.

**Pull request merged**
