### PR TITLE
[fix] Updating gitlabCi rules

### PR DESCRIPTION
**Pull request by phoinixgrr**
Signed-off-by: Akis Maziotis <akis.maziotis@mattermost.com>

#### Summary

Following up on https://git.internal.mattermost.com/mattermost/ci/pipelines/-/merge_requests/1 
We are updating GitLab Ci pipelines to support templating and dynamically including the pipeline corresponding to the name of the repository 

#### Ticket Link

Ticket: https://mattermost.atlassian.net/browse/DOPS-908

### CODE REVIEW

**Review by spirosoik — DISMISSED** [review]

**Review by pfltdv — DISMISSED** [review]
LGTM.

:100: that is great to have one repo for private pipelines.

**Comment by spirosoik** [comment]
we can move  on with the monorepo for pipelines if we all agree @pfltdv @phoinixgrr

**Comment by phoinixgrr** [comment]
@spirosoik  @pfltdv  Dropped your reviews with: https://github.com/mattermost/rtcd/pull/45/commits/c797acafe322a0bad70f30892488a9e70f982ba8 

Give this another go. Thanks!

**Comment by phoinixgrr** [comment]
> we can move on with the monorepo for pipelines if we all agree @pfltdv @phoinixgrr

Sure, That is my proposal. It will keep things tight and simple. no need to create a new repo for everytime we need a new pipeline for a project. Moreover we can easily support templating versioning, and dynamically injecting the repo name as include path for the actual pipeline. 
As we do here

**Comment by pfltdv** [comment]
> we can move on with the monorepo for pipelines if we all agree @pfltdv @phoinixgrr

+1(more votes if possible) for monorepos, it will make our lives easy, all pipelines will be at one place, that allow us more control and we may have reusable templates from some repo. Too many pros.

**Review by pfltdv — APPROVED** [review]

**Comment by phoinixgrr** [comment]
Pipeline fails on GitLab because  https://git.internal.mattermost.com/mattermost/ci/pipelines/-/merge_requests/1 hasn't been yet. 
Can be safely ignored

**Review by spirosoik — APPROVED** [review]

**Pull request merged**
